### ISSUE TITLE
Docker images not published

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/gateway-admision-controller#40]
# Details

**What steps did you take and what happened:**
Recent releases are not published to the gh docker repo.  https://github.com/k8s-at-home/gateway-admision-controller/pkgs/container/gateway-admision-controller

The latest seems to be 3.3.2

**What did you expect to happen:**
v3.5.0, v3.4.0 (from releases) present in the docker repo

**Anything else you would like to add:**

**Additional Information:**

**Comment by angelnu** [comment]
v3.4.0 was there but for v3.5.0 I had tagged it incorrectly (as v3.5) -> this lead to the missing upload.

It is there now. Thanks for reporting!
